Document: libapache2-mod-rpaf-gnif
Title: Debian libapache2-mod-rpaf-gnif Manual
Author: <insert document author here>
Abstract: This manual describes what libapache2-mod-rpaf-gnif is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libapache2-mod-rpaf-gnif/libapache2-mod-rpaf-gnif.sgml.gz

Format: postscript
Files: /usr/share/doc/libapache2-mod-rpaf-gnif/libapache2-mod-rpaf-gnif.ps.gz

Format: text
Files: /usr/share/doc/libapache2-mod-rpaf-gnif/libapache2-mod-rpaf-gnif.text.gz

Format: HTML
Index: /usr/share/doc/libapache2-mod-rpaf-gnif/html/index.html
Files: /usr/share/doc/libapache2-mod-rpaf-gnif/html/*.html
